In [4]:
import numpy as np
a = np.zeros(3)
print(a)
type(a)

[0. 0. 0.]


numpy.ndarray

In [7]:
b = np.ones(3)
print(b)
type(b[0])

[1. 1. 1.]


numpy.float64

In [9]:
b = np.linspace(2,10,5)
print(b)

[ 2.  4.  6.  8. 10.]


In [14]:
a_list = [1,3,4,5,6]
a = np.array([a_list])
print(a)
a.shape


[[1 3 4 5 6]]


(1, 5)

In [15]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])
print("Shape of 1D array:", arr.shape)  # Output: (5,)

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of 2D array:", arr_2d.shape)  # Output: (2, 3)

# Create a 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Shape of 3D array:", arr_3d.shape)  # Output: (2, 2, 2)


Shape of 1D array: (5,)
Shape of 2D array: (2, 3)
Shape of 3D array: (2, 2, 2)


In [21]:


# Generate a 1D array of 5 random numbers between 0 and 1
random_array_1d = np.random.randint(10,size=5)
print("1D array of random numbers:", random_array_1d)

# Generate a 2D array of random integers between 0 and 10
random_array_2d = np.random.randint(0, 10, size=(3, 3))
print("2D array of random integers:\n", random_array_2d)

# Generate a 3D array of random numbers from a normal distribution
random_array_3d = np.random.randn(2, 2, 2)
print("3D array of random numbers from normal distribution:\n", random_array_3d)


1D array of random numbers: [5 4 9 4 9]
2D array of random integers:
 [[7 6 6]
 [2 0 0]
 [7 0 5]]
3D array of random numbers from normal distribution:
 [[[ 0.63355658  1.31917332]
  [ 0.69963237  1.41170794]]

 [[ 0.04451156 -0.85648339]
  [-0.87195735  0.74610148]]]
